# Generated by Django 5.1.1 on 2024-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(default='no link'),
            preserve_default=False,
        ),
    ]
