# Generated by Django 5.1.1 on 2024-09-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author_Details',
        ),
    ]
