# Generated by Django 5.1.1 on 2024-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_rename_authors_author_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_details',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
