# Generated by Django 5.1.1 on 2024-09-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author_details',
            options={'ordering': ('name',), 'verbose_name_plural': 'Authors'},
        ),
    ]
